### ISSUE TITLE
[Bug] Minimized application doesnt open, when launching application again ** duplicate **

### ISSUE THREAD

**Issue by LTMX** [unitycoder/UnityLauncherPro#129] opened 2023-07-25 14:54 UTC

**Comment by unitycoder** [comment] 2023-07-29 08:50
Can you list the steps how it happens?

I tried rename & refresh, or rename & launch, no crash.

**Comment by LTMX** [comment] 2023-08-21 17:24
Okay I rediagnosed the bug :
It seems when trying to open ULP from the windows's task bar after ULP was minimized to the system tray, it opens up briefly and gets instantly minimized again to the system tray... so we can only relaunch it from the tray

**Comment by unitycoder** [comment] 2023-08-23 17:49
if you can screenshot your settings tab, i can try with similar settings.
is that on win10 or 11?
does it happen on pc start (if you have enabled run on start or minimize at start) ?

**Comment by unitycoder** [comment] 2023-08-24 18:02
ah ok! that one is this issue:
https://github.com/unitycoder/UnityLauncherPro/issues/67

seems to be surprisingly complicated to "wake up" (same) application from tray..

**Comment by unitycoder** [comment] 2023-08-28 13:36
i'll close this one, can follow that other issue! https://github.com/unitycoder/UnityLauncherPro/issues/67

and this settings blocks opening multiple copies (thats why the 2nd exe disappears)
![image](https://github.com/unitycoder/UnityLauncherPro/assets/5438317/51a6c38f-e0f8-4767-b014-609e7424d087)

**Closed** 2023-08-28 13:36 UTC

**Comment by unitycoder** [comment] 2023-08-30 13:20
tried to close as duplicate, but apparently cannot do it from that close button dropdown..

Duplicate of https://github.com/unitycoder/UnityLauncherPro/issues/67
